2021-03-20 13:14:55,493 INFO    MainThread:12495 [wandb_setup.py:_flush():69] setting env: {}
2021-03-20 13:14:55,493 INFO    MainThread:12495 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-20 13:14:55,493 INFO    MainThread:12495 [wandb_init.py:_log_setup():334] Logging user logs to /content/self-unsupervised-low-res-speech/wandb/run-20210320_131455-2z2uopq3/logs/debug.log
2021-03-20 13:14:55,493 INFO    MainThread:12495 [wandb_init.py:_log_setup():335] Logging internal logs to /content/self-unsupervised-low-res-speech/wandb/run-20210320_131455-2z2uopq3/logs/debug-internal.log
2021-03-20 13:14:55,494 INFO    MainThread:12495 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f596dbf3c90>
2021-03-20 13:14:55,494 INFO    MainThread:12495 [wandb_init.py:init():367] calling init triggers
2021-03-20 13:14:55,495 INFO    MainThread:12495 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-03-20 13:14:55,495 INFO    MainThread:12495 [wandb_init.py:init():416] starting backend
2021-03-20 13:14:55,495 INFO    MainThread:12495 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-03-20 13:14:55,530 INFO    MainThread:12495 [backend.py:ensure_launched():123] starting backend process...
2021-03-20 13:14:55,569 INFO    MainThread:12495 [backend.py:ensure_launched():128] started backend process with pid: 12548
2021-03-20 13:14:55,576 INFO    MainThread:12495 [wandb_init.py:init():421] backend started and connected
2021-03-20 13:14:55,634 INFO    MainThread:12495 [wandb_init.py:init():461] updated telemetry
2021-03-20 13:14:55,635 INFO    MainThread:12495 [wandb_init.py:init():480] communicating current version
2021-03-20 13:14:56,359 INFO    MainThread:12495 [wandb_init.py:init():485] got version response 
2021-03-20 13:14:56,359 INFO    MainThread:12495 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-20 13:14:56,664 INFO    MainThread:12495 [wandb_init.py:init():518] starting run threads in backend
2021-03-20 13:14:58,259 INFO    MainThread:12495 [wandb_run.py:_console_start():1480] atexit reg
2021-03-20 13:14:58,259 INFO    MainThread:12495 [wandb_run.py:_redirect():1343] redirect: SettingsConsole.WRAP
2021-03-20 13:14:58,260 INFO    MainThread:12495 [wandb_run.py:_redirect():1378] Wrapping output streams.
2021-03-20 13:14:58,260 INFO    MainThread:12495 [wandb_run.py:_redirect():1394] Redirects installed.
2021-03-20 13:14:58,260 INFO    MainThread:12495 [wandb_init.py:init():542] run started, returning control to user process
2021-03-20 13:14:58,260 INFO    MainThread:12495 [wandb_run.py:_config_callback():733] config_cb None None {}
2021-03-20 13:14:59,000 INFO    MainThread:12495 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-20 13:14:59,000 INFO    MainThread:12495 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-20 13:15:51,865 INFO    MainThread:12495 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-20 13:15:54,224 INFO    MainThread:12495 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-20 13:15:54,224 INFO    MainThread:12495 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-20 13:15:54,251 INFO    MainThread:12495 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-20 13:15:54,261 INFO    MainThread:12495 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-20 13:15:54,261 INFO    MainThread:12495 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-20 13:15:54,295 INFO    MainThread:12495 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-20 13:15:54,440 INFO    MainThread:12495 [wandb_run.py:_config_callback():733] config_cb None None {}
2021-03-20 13:16:28,527 INFO    MainThread:12495 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-20 13:16:28,527 INFO    MainThread:12495 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-20 13:16:48,202 INFO    MainThread:12495 [wandb_run.py:_atexit_cleanup():1450] got exitcode: 0
2021-03-20 13:16:48,203 INFO    MainThread:12495 [wandb_run.py:_restore():1422] restore
2021-03-20 13:16:48,205 INFO    MainThread:12495 [wandb_run.py:_restore():1422] restore
